### ISSUE TITLE
Bounty factory for web frameworks

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/bounties#2]
Create several bounties for popular frameworks:

- [ ] AngularJS
- [x] Vue.js #14 
- [x] Svelte #15 
- [x] Next.js (FE only, no SSR) #13
- [x] React Native https://github.com/waku-org/js-waku/issues/1327#issue-1695783137 #12
- [ ] Also provide 2-3 free for all bounties on Gitcoin and Replit of any original ideas for Waku

Bounty output should be:

1. Build a small app using Waku (any use case), idea should be pre-approved as part of hacker selection. Must be MIT+Apache2.0
2. Write a blog post (on your blog) that comes with the app to build said app (must be CC0). Blog post title must include keyword (to be specified, something like build app without BE)
3. Write a Twitter thread about it.
4. Bonus cash if original idea (need to think how we formulate that).

We can then take the result and adapt it/migrate it to our examples and our docs.

Content for Bounties:

# Build dApp of Your Choice Using Waku (Decentralized Communication) and {web framework}

## Context

Waku Is Uncompromising Web3 Communication at Scale.
A family of robust, censorship-resistant communication protocols, designed to enable privacy-focused messaging for web3 apps.

The JavaScript implementation of Waku, [js-waku](https://github.com/waku-org/js-waku/), enables web apps to utilize the Waku network for off-chain message transmission.

Disclaimer: Waku is **experimental**, you may find blocking issues while developing your web app. We will prioritize their resolution to unblock you, which means you may have to pause development until done.
Thank you for your patience and understanding.

**Your participation in this bounty is subject to your acceptance of our terms and conditions.**
Please see https://github.com/waku-org/bounties#applying-for-a-bounty for details.

## Rewards

1000 DAI.

## Timeframe to Completion

Once the application is approved, the result must be submitted within 30 days.

## Application Evaluation

To ensure you are selected for this bounty, provide the following information:

- Describe the approach you will take to tackle the bounty.
- A timeline within which you expect to deliver the bounty.
- Any previous relevant work you have done.

## Bounty

This bounty specifies 3 deliverables, all needed to consider the bounty complete. Partial delivery of the bounty will **not** make you eligible for the prize. The deliverables are:

1. A simple web app written using {web framework}
2. A post on your blog to guide a reader through building the web app.
3. A tweet thread explaining how your web app works and leverages Waku for private, decentralized communications.

The bounty aims to inspire developers to build applications using Waku. This is why the web app's nature is up to the hacker. However, to push for creative use of Waku, we **will not accept chat apps or chat features** using Waku.

{add a note about T&C}

### Impact

The web ecosystem has a number of frameworks that each have different pre-configured bundler.
To ensure a smooth dev ex for all web developer, it is best to not only test `@waku/sdk` against the last version of each framework but also provide examples on how `@waku/sdk` can be used with concepts unique of said framework (e.g. React Components).

It is difficult to have expert of all frameworks in a team, so best to outsource this to the community. 

#### (1) Web App

Build a web app using {web framework}.

### Acceptance Criteria

You must fulfil all the criteria below to consider the bounty valid:

- Must use best and idiomatic practices for {web framework}.
- Must use the latest stable version of {web framework} and `@waku/sdk`
- Must be a frontend only, browser web app (no backend, no NodeJS, no SSR, no lambda function otherwise it's not decentralized). {Remove this part for react native}
- Must use TCP transport instead of websocket {only for react native}
- Must **not** be a chat app or use Waku for chat messages. Be creative!
- Must use Waku for a core communication feature.
- The web app must be deployed on IPFS or permissionless decentralized storage solutions.
- In addition to that, you are free to host the website on a web server of your choice, such as GitHub pages (not mandatory)
- All code must be licensed under MIT+Apache2.0.

Please describe your idea as part of the application to ensure your submission will fulfil the criteria.

We may add high-quality submissions to our [example repo](https://github.com/waku-org/js-waku-examples).

### (2) Blogpost

Write a blog guide that takes a reader through building your web app.
The reader should be able to build a working web app by following your guide.

We recommend building a simple web app to make the guide easy to write and read.

The blog post must be licensed under CC0.

High-quality guides maybe be edited and added to the Waku docs at https://docs.waku.org/.

#### Acceptance Criteria

We prefer moderate-length articles, ideally between 1500 to 3000 words (excluding code). While not mandatory, we strongly encourage you to adhere to this guideline.

When relevant, reference concepts and definitions from our documentation (https://docs.waku.org) and provide a link to our community (https://docs.waku.org/community) for additional assistance.

Avoid submitting articles you have already published or have a high plagiarism score to existing ones.

#### (3) Twitter thread

Post a Twitter thread from your Twitter account that describes how the web app uses Waku.

For example, if you build a tic-tac-toe game, describe how your web app finds another player using Waku and then exchange the moves over Waku.

#### Acceptance Criteria

- The thread must tag the `@Waku_org` Twitter account.
- The thread must explain how Waku is enabling this use case/app.

### Resources

Learn more about Waku at https://docs.waku.org/.
Join our Discord to get support at https://discord.waku.org/.
Various examples available at https://github.com/waku-org/js-waku-examples/.

**Comment by b4s36t4** [comment]
@fryorcraken Can I work on `Next.JS`. Where can I share my idea? in discord?

**Comment by fryorcraken** [comment]
> @fryorcraken Can I work on `Next.JS`. Where can I share my idea? in discord?

You can have dibs on it once we have set it up :)

**Comment by b4s36t4** [comment]
Ok, cool. Thanks!

**Comment by fryorcraken** [comment]
@hackyguru @waku-org/js-waku-developers @LordGhostX keen to have a review on the content of this bounty. If looking good, I can create an issue/bounty per framework

**Comment by danisharora099** [comment]
Looks good to me! 

Some comments/suggestions:
- Adding a section on "Submission Guidelines" --  details around how participants should submit their work
- Specifying how and when the rewards will be distributed
- Adding a section on "Intellectual Property" -- it might be beneficial to clarify who owns the rights to the submitted work
- Adding a "FAQs" section?

**Comment by weboko** [comment]
Love this one 
> Must not be a chat app or use Waku for chat messages. Be creative!

Have nothing to add on top.

**Comment by fryorcraken** [comment]
> Looks good to me!
> 
> Some comments/suggestions:
> 
>     * Adding a section on "Submission Guidelines" --  details around how participants should submit their work
> 
>     * Specifying how and when the rewards will be distributed
> 
>     * Adding a section on "Intellectual Property" -- it might be beneficial to clarify who owns the rights to the submitted work
All covered with

``` 
**Your participation in this bounty is subject to your acceptance of our terms and conditions.**
Please see https://github.com/waku-org/bounties#applying-for-a-bounty for details.
```

>     * Adding a "FAQs" section?

What kind of FAQ?

**Comment by fryorcraken** [comment]
> @fryorcraken Can I work on `Next.JS`. Where can I share my idea? in discord?

https://github.com/waku-org/bounties/issues/13 @b4s36t4

**Comment by b4s36t4** [comment]
Hey @fryorcraken thanks. I read the description for the bounty. My only concern is deploying app to ipfs related solutions. Can I deploy it to vercel Or it has to be decentralized as well?

**Comment by fryorcraken** [comment]
> Hey @fryorcraken thanks. I read the description for the bounty. My only concern is deploying app to ipfs related solutions. Can I deploy it to vercel Or it has to be decentralized as well?

Can you please clarify the concern? IPFS provides docs for this use case: https://docs.ipfs.tech/how-to/websites-on-ipfs/single-page-website/

The point is to show that one can indeed build a fully decentralized dApp using Waku.

**Comment by fryorcraken** [comment]
Several bounties are now open.
Let's hold the rest for now so we can see how it goes and we learn some lessons.

**Comment by seichris** [comment]
I hacked a chrome extension for ETH Istanbul. I could turn it into a template as well
